name: task_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  circular_chart_flutter: ^0.0.2
  google_fonts: ^4.0.4
  intl: ^0.18.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
